# Generated by Django 3.2 on 2023-10-04 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20231004_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='order_history',
        ),
    ]
