# Generated by Django 3.2 on 2023-10-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_delivery_address',
        ),
    ]
