# Generated by Django 3.2 on 2023-09-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20230403_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='challenge',
            name='image2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='challenge',
            name='image3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='challenge',
            name='image4',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
