# Generated by Django 3.2 on 2023-10-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_auto_20230918_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='content',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='intro',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='outro',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='steps',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='tips',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
