# Generated by Django 3.2 on 2023-08-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='friendly_name',
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='name',
        ),
        migrations.AddField(
            model_name='postcategory',
            name='excerpt',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='title',
            field=models.CharField(default='Default Title', max_length=200),
        ),
    ]
