# Generated by Django 3.2 on 2023-09-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_alter_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, max_length=140),
        ),
    ]
